engines:
  checkstyle:
    enabled: true
    channel: "beta"
  pmd:
    enabled: true
    channel: "beta"
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true

ratings:
  paths:
  - "**.java"
exclude_paths: []