language: java
jdk:
  - oraclejdk8

env:
  global:
    - BUILD_TIMESTAMP=$(date +%Y-%m-%d)
    - BINTRAY_USERNAME="jeslopalo"

after_success: "./src/main/scripts/build/cobertura.sh"

before_deploy: "echo '$(date +%Y-%m-%d) - Deploying to bintray'"

deploy:
  skip_cleanup: true
  provider: script
  script: mvn deploy -P release --batch-mode --settings .travis.settings.xml
  on:
    tags: true
    jdk: oraclejdk8

after_deploy: "echo '$(date +%Y-%m-%d) - Artifact has been deployed into bintray!'"
