language: java
jdk:
  - oraclejdk8

env:
  global:
    - BINTRAY_USERNAME="jeslopalo"

after_success: "./src/main/scripts/build/cobertura.sh"

before_deploy: echo "$(date +%Y-%m-%d) - Deploying to bintray"

deploy:
  skip_cleanup: true
  provider: script
  script: mvn deploy -P release -Dmaven.test.skip=true --batch-mode --settings .travis.settings.xml
  on:
    tags: true
    jdk: oraclejdk8

after_deploy: echo "$(date +%Y-%m-%d) - Artifact has been deployed into bintray!"


addons:
  code_climate:
    repo_token: f2f04202004fc05f09262dee7e749ceebf7207fcfeea55de111fff1f9e016e96